<a href="https://colab.research.google.com/github/manikanta741/datamining/blob/main/arrp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#scalar multiplication
import numpy as np

# Define the scalar and the matrix
scalar = 5
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Perform scalar multiplication
result = scalar * matrix

# Print the result
print("Scalar:", scalar)
print("Matrix:")
print(matrix)
print("Result of scalar matrix multiplication:")
print(result)


Scalar: 5
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Result of scalar matrix multiplication:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [2]:
#Add two matrices.
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a+b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [3]:
#subtraction
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a-b)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
result=np.dot(a,b)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [6]:
#Check whether two matrices are equal or not.
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])


are_equal = np.array_equal(matrix1, matrix2)


print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Are the matrices equal?", are_equal)


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Are the matrices equal? True


In [7]:
import numpy as np


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


diagonal_sum = np.trace(matrix)

print("Matrix:")
print(matrix)
print("Sum of the main diagonal elements:", diagonal_sum)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the main diagonal elements: 15


In [8]:
import numpy as np

# Define the matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the size of the matrix (assuming it's square)
n = matrix.shape[0]

# Compute the sum of the minor diagonal elements
minor_diagonal_sum = np.sum(np.fliplr(matrix).diagonal())

# Print the result
print("Matrix:")
print(matrix)
print("Sum of the minor diagonal elements:", minor_diagonal_sum)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the minor diagonal elements: 15
