<a href="https://colab.research.google.com/github/manikanta741/datamining/blob/main/numpy%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)
print(a.ndim)
print(a.dtype)

[1 2 3 4 5 6]
1
int64


In [8]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
print(b.itemsize)
print(b.size)
print(b.shape)

[[1 2 3]
 [4 5 6]]
2
8
6
(2, 3)


In [10]:
c=np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
d=np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
e=np.arange(1,6)
print(e)

[1 2 3 4 5]


In [16]:
f=np.linspace(1,5,10)
print(f)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
print()

In [17]:
print(b)
print(b.shape)
print(b.reshape(3,2))

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(b.ravel())

[1 2 3 4 5 6]


In [22]:
print(a.min())
print(b.min())

1
1


In [23]:
print(b.sum())

21


In [25]:
g=np.sqrt(b)
print(g)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [26]:
h=np.mean(a)
print(h)


3.5


In [28]:
i=np.std(a)
print(i)

1.707825127659933
