<a href="https://colab.research.google.com/github/manikanta741/datamining/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


In [4]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int64


In [12]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [15]:
print(c[1,3])
print(c[0,:])
print(c[:,3])

8
[1 2 3 4]
[4 8]


In [17]:
d=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(d)
print(d.ndim)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
3


In [20]:
s=np.zeros((2,3))
print(s)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
r=np.ones((2,3))
print(r)


[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
t=np.ones((2,3,2))
print(t)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [25]:
z=np.full((2,3),99)
print(z)

[[99 99 99]
 [99 99 99]]


In [26]:
y=np.identity(5)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
p=np.random.rand(4,2)
print(p)

[[0.3969372  0.40402066]
 [0.98136976 0.81008806]
 [0.6470194  0.07800331]
 [0.6947164  0.54500075]]


In [31]:
h=np.array([2,3,4,5])
print(h)

[2 3 4 5]


In [39]:
g=np.array([1,2,3,4])
g=a
g[0]=10
print(a)
print(g)

[10  2  3  4  5]
[10  2  3  4  5]


In [41]:
g=np.array([1,2,3,4])
g=a.copy()
g[0]=10
print(a)
print(g)

[10  2  3  4  5]
[10  2  3  4  5]


In [42]:
print(a+2)

[12  4  5  6  7]
