<a href="https://colab.research.google.com/github/manikanta741/datamining/blob/main/numpyarr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#scalar multiplication
import numpy as np

# Define the scalar and the matrix
scalar = 5
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Perform scalar multiplication
result = scalar * matrix

# Print the result
print("Scalar:", scalar)
print("Matrix:")
print(matrix)
print("Result of scalar matrix multiplication:")
print(result)


Scalar: 5
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Result of scalar matrix multiplication:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [4]:
#Add two matrices.
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a+b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [5]:
#subtraction
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a-b)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
result=np.dot(a,b)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [7]:
#Check whether two matrices are equal or not.
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])


are_equal = np.array_equal(matrix1, matrix2)


print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)
print("Are the matrices equal?", are_equal)


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Are the matrices equal? True


In [8]:
import numpy as np


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


diagonal_sum = np.trace(matrix)

print("Matrix:")
print(matrix)
print("Sum of the main diagonal elements:", diagonal_sum)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the main diagonal elements: 15


In [9]:
import numpy as np

# Define the matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the size of the matrix (assuming it's square)
n = matrix.shape[0]

# Compute the sum of the minor diagonal elements
minor_diagonal_sum = np.sum(np.fliplr(matrix).diagonal())

# Print the result
print("Matrix:")
print(matrix)
print("Sum of the minor diagonal elements:", minor_diagonal_sum)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the minor diagonal elements: 15


In [10]:
def sum_rows_and_columns(matrix):
    num_rows = len(matrix)
    num_cols = len(matrix[0])

    # Calculate the sum of each row
    row_sums = [sum(row) for row in matrix]

    # Calculate the sum of each column
    column_sums = [sum(matrix[row][col] for row in range(num_rows)) for col in range(num_cols)]

    return row_sums, column_sums

# Example usage:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

row_sums, column_sums = sum_rows_and_columns(matrix)
print("Sum of each row:", row_sums)
print("Sum of each column:", column_sums)


Sum of each row: [6, 15, 24]
Sum of each column: [12, 15, 18]


In [11]:
#Find the sum of each row and column of a matrix.
def sum(m):
  rows=len(matrix)
  columns=len(matrix[0])
  row_sums=[sum(row) for row in matrix]
  column_sums=[sum(matrix[row][col] for row in range(rows)) for col in range(columns)]
  return row_sums,column_sums
m=[[1,2,3],
   [4,5,6],
   [7,8,9]]
print(row_sums,column_sums)

[6, 15, 24] [12, 15, 18]


In [12]:

import numpy as np

# Example usage:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

np_matrix = np.array(matrix)
transposed_matrix = np_matrix.T
print(transposed_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
#determinant of matrix
print(np.linalg.det(np_matrix))

0.0


In [14]:
#identity matriix
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#from numpy.linalg import inv,det,eig,,svd,norm,solve
import numpy as np
from numpy.linalg import inv, det, eig, svd, solve, norm
# Example matrix
A = np.array([[1, 2], [3, 4]])

# Inverse of matrix A
A_inv = inv(A)
print("Inverse of A:\n", A_inv)



# Determinant of matrix A
A_det = det(A)
print("Determinant of A:", A_det)





# Eigenvalues and eigenvectors of matrix A
eigenvalues, eigenvectors = eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)



# SVD of matrix A
U, S, Vt = svd(A)
print("U matrix:\n", U)
print("Singular values:", S)
print("V^T matrix:\n", Vt)




# Example system: Ax = b
b = np.array([5, 11])

# Solve for x
x = solve(A, b)
print("Solution x:", x)





# Norm of matrix A
A_norm = norm(A)
print("Norm of A:", A_norm)


Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
U matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
V^T matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
Solution x: [1. 2.]
Norm of A: 5.477225575051661


In [16]:
#sparse matrix
from scipy.sparse import csr_matrix,csc_matrix
# Define a dense matrix
dense_matrix = np.array([[0, 0, 3], [4, 0, 0], [0, 0, 0]])

# Convert to CSR format
csr = csr_matrix(dense_matrix)
print("CSR Matrix:\n", csr)
print("CSR Matrix (dense):\n", csr.toarray())


CSR Matrix:
   (0, 2)	3
  (1, 0)	4
CSR Matrix (dense):
 [[0 0 3]
 [4 0 0]
 [0 0 0]]


In [17]:
# Convert to CSC format
csc = csc_matrix(dense_matrix)
print("CSC Matrix:\n", csc)
print("CSC Matrix (dense):\n", csc.toarray())


CSC Matrix:
   (1, 0)	4
  (0, 2)	3
CSC Matrix (dense):
 [[0 0 3]
 [4 0 0]
 [0 0 0]]


In [18]:
#symmetric matrix
import numpy as np

matrix = np.array([[1, 2, 3],
                   [2, 4, 5],
                   [3, 5, 6]])
# Check if matrix is symmetric
is_symmetric = np.allclose(matrix, matrix.T)
print("Is the matrix symmetric?", is_symmetric)


Is the matrix symmetric? True


In [19]:
#lower triangular matrix
import numpy as np

# Define the size of the matrix
n = 4

# Create a matrix with random values
matrix = np.random.randint(1, 10, size=(n, n))

# Create the lower triangular matrix
lower_triangular_matrix = np.tril(matrix)

print("Original Matrix:\n", matrix)
print("Lower Triangular Matrix:\n", lower_triangular_matrix)


Original Matrix:
 [[3 5 7 9]
 [1 3 9 7]
 [7 3 8 9]
 [9 1 3 9]]
Lower Triangular Matrix:
 [[3 0 0 0]
 [1 3 0 0]
 [7 3 8 0]
 [9 1 3 9]]


In [20]:
#upper triangular matrix
import numpy as np

# Define the size of the matrix
n = 4

# Create a matrix with random values
matrix = np.random.randint(1, 10, size=(n, n))

# Create the upper triangular matrix
upper_triangular_matrix = np.triu(matrix)

print("Original Matrix:\n", matrix)
print("Upper Triangular Matrix:\n", upper_triangular_matrix)


Original Matrix:
 [[5 1 2 5]
 [3 6 3 2]
 [5 5 7 3]
 [8 7 4 2]]
Upper Triangular Matrix:
 [[5 1 2 5]
 [0 6 3 2]
 [0 0 7 3]
 [0 0 0 2]]


In [21]:
#sum of upper triangular matrix
import numpy as np

# Define the size of the matrix
n = 4

# Create a matrix with random values
matrix = np.random.randint(1, 10, size=(n, n))

# Create the upper triangular matrix
upper_triangular_matrix = np.triu(matrix)

# Compute the sum of the upper triangular matrix
upper_triangular_sum = np.sum(upper_triangular_matrix)

print("Original Matrix:\n", matrix)
print("Upper Triangular Matrix:\n", upper_triangular_matrix)
print("Sum of Upper Triangular Matrix:", upper_triangular_sum)


Original Matrix:
 [[6 8 4 2]
 [1 9 1 5]
 [2 9 6 7]
 [6 4 7 6]]
Upper Triangular Matrix:
 [[6 8 4 2]
 [0 9 1 5]
 [0 0 6 7]
 [0 0 0 6]]
Sum of Upper Triangular Matrix: 54
