<a href="https://colab.research.google.com/github/manikanta741/datamining/blob/main/numpy%20slicing%20and%20indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a[0])
print(a[-1])
print(a[1:2])
print(a[0:])

[1 2 3]
1
3
[2]
[1 2 3]


In [6]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(b[1,2])

6


In [8]:
print(b[0:2,1])

[2 5]


In [9]:
print(b[-1])

[7 8 9]


In [10]:
for cell in b.flat:
  print(cell)

1
2
3
4
5
6
7
8
9


In [14]:
import numpy as np
b=np.arange(6).reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [15]:
b=np.arange(6,12).reshape(3,2)
print(b)

[[ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
#hstack
#hsplit
#vstack
#vsplit