<a href="https://colab.research.google.com/github/manikanta741/datamining/blob/main/pythonlife.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#int to dec
import decimal
integer=17
dv=decimal.Decimal(integer)
print(dv)
print(integer/1)
print(float(integer))

17
17.0
17.0


In [ ]:
#rev of a str
sr="madam"
print(sr[::-1])

madam


In [ ]:
#no of vowels
vowels="aeiou"
count=0
str1="manikanta"
for i in str1:
  if i in vowels:
    count+=1
print("no of vowels is",count)


no of vowels is 4


In [ ]:
#no of constants
vowels="aeiou"
count=0
str1="manikanta"
for i in str1:
  if i not in vowels:
    count+=1
print("no of constants is",count)

no of constants is 5


In [ ]:
#no of occurances of a char in str
str1="manikanta"
character='a'
count=0
for i in str1:
  if i==character:
    count+=1
print("no of occurances of character is",{count})


no of occurances of character is {3}


In [ ]:
#fibanoccci series
num=10
a=0
b=1

for i in range(0,num):
  print(a)
  a,b=b,a+b


0
1
1
2
3
5
8
13
21
34


In [ ]:
#max
l1=[9,1,8,2,4,6,5,3]
max=l1[0]
for i in l1:
  if i>max:
    max=i
print(max)

9


In [ ]:
#min
l1=[9,1,8,2,4,6,5,3]
min=l1[0]
for i in l1:
  if i<min:
    min=i
print(min)

1


In [ ]:
def find_middle(list):
  n=len(list)
  if n==0:
    return none
  else:
    if n%2==0:
      return list[n//2-1],list[n//2]
    else:
      return list[n//2]
list=[1,2,3,4,5,6]
print(find_middle(list))

(3, 4)


In [ ]:
#convert lst to string
l2=["1","2","3","4"]
str1=",".join(l2)
print(str1)

1,2,3,4


In [ ]:
l3=[1,2,3,4,5,6]
str2=",".join(map(str,list))
print(str2)

1,2,3,4,5,6


In [ ]:
#convert entire list to str
l4=[1,2,3,"mani"]
print(str(l4))

[1, 2, 3, 'mani']


In [ ]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=l1+l2
print(l3)
print(l1.extend(l2))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
None


In [ ]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l1.extend(l2)
print(l1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#anagrams
str1="LiSten"
str2="SIlent"
s1=str1.upper()
s2=str2.upper()
if sorted(s1)==sorted(s2):
  print("anagram")
else:
  print("not anagram")

anagram


In [ ]:
str1="madam"
if str1==str1[::-1]:
  print("palindrome")
else:
  print("not palindrome")

palindrome


In [ ]:
def is_palindrome(s):
    # Convert to lowercase and remove spaces for consistent checking
    s = s.replace(" ", "")

    return s == s[::-1]  # Compare the string with its reverse

s=input("enter a string")
if is_palindrome(s):
    print(f"'{s}' is a palindrome.")
else:
    print(f"'{s}' is not a palindrome.")

enter a stringmadam
'madam' is a palindrome.


In [ ]:
# count of white spaces
str1="p yth on"
print(str1.count(" "))

2


In [ ]:
# no of ketters, spaces,digits
dig_count=0
letter_count=0
space_count=0
str1="mani kanta 4262"
for i in str1:
  if i.isdigit():
    dig_count+=1
  elif i.isalpha():
    letter_count+=1
  else:
    space_count+=1
print(dig_count)
print(letter_count)
print(space_count)

4
9
2


In [ ]:
#special char
dig_count=0
letter_count=0
space_count=0
spchar_count=0
str1="mani@ kanta$ 42&**(62"
for i in str1:
  if i.isdigit():
    dig_count+=1
  elif i.isalpha():
    letter_count+=1
  elif i.isspace():
    space_count+=1
  else:
    spchar_count+=1
print(dig_count)
print(letter_count)
print(space_count)
print(spchar_count)

4
9
2
6


In [ ]:
#special chars
def count_special_characters(input_string):
    special_char_count = 0

    for char in input_string:
        if not char.isalnum() and not char.isspace():
            special_char_count += 1

    return special_char_count

# Example usage
input_string = input("Enter a string: ")
special_chars = count_special_characters(input_string)
print(f"Special characters: {special_chars}")

Enter a string: mani $aka%^nta 42%^62
Special characters: 5


In [ ]:
#removing white spaces
str1="mani kanta"
print(str1.replace(" ",""))
print(str1.strip())

manikanta
mani kanta


In [ ]:
#removing leading and tailing spaces
str1=" mani kanta  "
print("original string:-",str1)
print("removing leading and tailing spaces:-",   str1.strip())

print("removing leading spaces:-",str1.lstrip())

print("removing tailing spaces:-",str1.rstrip())




original string:-  mani kanta  
removing leading and tailing spaces:- mani kanta
removing leading spaces:- mani kanta  
removing tailing spaces:-  mani kanta


In [ ]:
#shuffling of array or list
import random
list=[1,2,3,4,5]
random.shuffle(list)
print(list)

[5, 2, 3, 4, 1]


In [ ]:
#num divisible by7 and not div by 5
l=[]
for i in range(2000,3200):
  if i%7==0 and i%5!=0:
    l.append(i)
print(i)

3199


In [ ]:
#factorial
fact=1
num=8
for i in range(1,num+1):
  if num==1:
    fact=1
  else:
    fact=fact*i
  print(fact)

40320


In [ ]:
#generate list,tuple
inp="2,3,4,5"
list=inp.split(",")
print(list)
print(tuple(list))

['2', '3', '4', '5']
('2', '3', '4', '5')


In [ ]:
#getstring
user_input = input("Please enter your name: ")

#Print thestring
print(f"Hello, {user_input}! Welcome!")


Please enter your name: mani
Hello, mani! Welcome!


In [ ]:
#implement math
import math
c=50
h=30
d=int(input())
print(math.sqrt((2*c*d)/h))

100
18.257418583505537


In [ ]:
#generate random array of 3 rows and 5 columns
import numpy as np
import random
array=np.random.randint(0,10,size=(3,5))
print(array)

[[5 0 2 4 4]
 [2 9 6 4 5]
 [7 3 0 8 0]]


In [ ]:
#take  some words as input and then convert to list and produce result in alphabetical order
inp="without,hello,bag,world"
list=inp.split(",")
list.sort()
print(list)

['bag', 'hello', 'without', 'world']


In [3]:
#capitalize
str1="maNi kAnta"
print(str1.capitalize())

Mani kanta


In [6]:
def generate_array(x, y):
  """Generates a 2D array with elements i*j.

  Args:
    x: Number of rows.
    y: Number of columns.

  Returns:
    A 2D array of size x*y.
  """

  array = [[i * j for j in range(y)] for i in range(x)]
  return array

# Get input from the user
x = int(input("Enter the number of rows (X): "))
y = int(input("Enter the number of columns (Y): "))

# Generate the 2D array
result_array = generate_array(x, y)

# Print the array in a readable format
for row in result_array:
  print(row)

Enter the number of rows (X): 3
Enter the number of columns (Y): 5
[0, 0, 0, 0, 0]
[0, 1, 2, 3, 4]
[0, 2, 4, 6, 8]


In [9]:
# no of letters and digits
str2="hello world! 123"
dig_count=0
letter_count=0
for i in str2:
  if i.isdigit():
    dig_count+=1
  elif i.isalpha():
    letter_count+=1
print(dig_count)
print(letter_count)

3
10


In [22]:
#count of upper and lower
str2="Helloworld!"
upper_count=0
lower_count=0
for i in str2:
  if i.isupper():
    upper_count+=1
  else:
    lower_count+=1
print(upper_count)
print(lower_count)

1
10
